name: Documentation

on:
  push:
    branches: [main]
    paths:
      - 'docs/**'
      - 'src/**'
      - 'pyproject.toml'
  workflow_dispatch:

jobs:
  build-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev]"

    - name: Setup docs structure
      run: |
        if [ ! -d "docs" ]; then
          mkdir -p docs
          cd docs
          
          cat > conf.py << 'EOF'
        import os
        import sys
        sys.path.insert(0, os.path.abspath('../src'))

        project = 'XFinance SDK'
        copyright = '2024, X-Finance Team'
        author = 'X-Finance Team'

        extensions = [
            'sphinx.ext.autodoc',
            'sphinx.ext.viewcode',
            'sphinx.ext.napoleon',
        ]

        exclude_patterns = ['_build']
        html_theme = 'sphinx_rtd_theme'

        napoleon_google_docstring = True
        napoleon_numpy_docstring = True
        EOF
          
          cat > index.rst << 'EOF'
        XFinance SDK Documentation
        ==========================

        .. automodule:: xfinance
           :members:
           :undoc-members:
           :show-inheritance:

        Indices and tables
        ==================

        * :ref:`genindex`
        * :ref:`modindex`
        EOF
          
          cat > Makefile << 'EOF'
        SPHINXBUILD = sphinx-build
        BUILDDIR = _build

        html:
        	$(SPHINXBUILD) -b html . $(BUILDDIR)/html
        EOF
        fi

    - name: Build documentation
      run: |
        cd docs
        make html
        touch _build/html/.nojekyll

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/_build/html